export const REPLACE_IS_AUTH = 'REPLACE_IS_AUTH'
export const REPLACE_ERROR = 'REPLACE_ERROR'
export const REPLACE_ERROR_MESSAGE = 'REPLACE_ERROR_MESSAGE'
export const REPLACE_USERNAME = 'REPLACE_USERNAME'
export const REPLACE_PASSWORD = 'REPLACE_PASSWORD'
export const REPLACE_ERROR_EXIST_MESSAGE = 'REPLACE_ERROR_EXIST_MESSAGE'
export const REPLACE_ERROR_EXIST = 'REPLACE_ERROR_EXIST'

